language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install requests pyyaml pytest pytest-cov
  - pip install pandas
  - pip install numpy
  - pip install matplotlib
  - pip install -r requirements.txt


script:
- pytest --cov=./